library(stringr)
library(ggplot2)
library(dplyr)
library(car)
library(lattice)
library(gridExtra)
library(foreign)
library(readxl)
library(rJava)
library(memoise)
library(KoNLP)
library(wordcloud)
library(multilinguer)
library(httr)
library(rvest)
library(RSelenium)
library(KeyboardSimulator)
library(readr)
library(xlsx)


